In [17]:
from gym import Env
from gym.spaces import Discrete, Box, Dict, MultiBinary, Tuple


In [12]:
test = Discrete(8)
test.sample()

0

In [1]:
import numpy as np

In [6]:
a = [1, 2, 3]
b = [4, 5, 6]
test = np.zeros([len(a), len(b)])
test

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
x = Discrete(3)
y = Tuple((Box(0, 100, (3,)), Box(0, 100, (3,))))
x.n

3

In [25]:
new_test = np.zeros([y, x.n])
new_test

TypeError: 'Tuple' object cannot be interpreted as an integer

In [32]:
f = [0,1,2]
len(f)

3

In [38]:
g = Tuple([1,2,3],[4,5,6])
len(g)

AssertionError: Elements of the tuple must be instances of gym.Space

In [34]:
q = np.zeros([len(g), len(f)])
q

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
np.zeros([8, 4])


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
np.random.choice([1,2,3,4,])

3

In [70]:
q = np.zeros([9, 4])
q[0][3] = 1
state = np.zeros(8)
state_1 = np.full(8, 1)
actions = np.arange(4)
q[sum(state_1).astype(int)][np.random.choice(actions)]

0.0

In [56]:
sum(state)

0.0

In [61]:
np.random.choice(actions)

3

In [72]:
np.max(q[sum(state).astype(int)])

1.0

In [81]:
q = np.zeros([1, 4])
q


array([[0., 0., 0., 0.]])

In [82]:
state = np.array([1.53, 5.234, 67.12])
state

array([ 1.53 ,  5.234, 67.12 ])

In [85]:
np.vstack((q, np.zeros(4)))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [86]:
np.zeros([10, 10, 4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
      